[package]
name = "rustqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.9" # for loading the db into memory
anyhow = "1.0.68" # error handling
clap = { version = "4.5.53", features = ["derive"] }
