[package]
name = "rustqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap = "0.7.0"  # for loading the db into memory
anyhow = "1.0.68" # error handling
clap = { version = "4.5.53", features = ["derive"] }
